FROM node:20-slim AS builder
WORKDIR /app

COPY package.json package-lock.json ./
COPY script ./script
RUN apt-get update -y && apt-get install -y openssl && \
    apt-get install -y git wget curl

# RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:20-slim AS runner

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/.env ./.env
COPY --from=builder /app/resources ./resources

EXPOSE 3000

CMD ["npm", "run", "start"]
