FROM node:20-slim AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y openssl

COPY . .

RUN npm install
RUN npx prisma generate
RUN npm run build

FROM node:20-slim AS runner

WORKDIR /app
RUN apt-get update && apt-get install -y openssl

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "run", "start"]