services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./models:/models
    command: >
      --model /resources/models/Qwen3-1.7B-Q6_K.gguf
      --ctx-size 2048
      --host 0.0.0.0
      --port 5000
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p-task-assistant-nextjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - qdrant
      - llama-server
